export const employees = [
  {
    id: 1,
    name: "abc",
    role: "driver",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 2,
    name: "xyz",
    role: "driver",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 3,
    name: "abc",
    role: "electrician",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 4,
    name: "abc",
    role: "labor",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 5,
    name: "abc",
    role: "driver",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 6,
    name: "lmn",
    role: "plumber",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 7,
    name: "abc",
    role: "electritian",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
  {
    id: 8,
    name: "abc",
    role: "driver",
    phone: "0303189384",
    email: "abc@gmail.com",
  },
];

export const UserHistoryCols = ["Date", "Company Name", "Services", "Quote"];
export const CompanyHistoryCols = [
  "Date",
  "Customer Name",
  "Services",
  "Quote",
  "Status",
];
export const UserHistory = [
  {
    id: 1,
    date: "12 jan, 2023",
    company: "Shehroz & Co",
    services: "Packing",
    price: "12, 500",
    status: "completed",
    name: "hamza",
  },
  {
    id: 2,
    date: "2 feb, 2023",
    company: "Hakim & Co",
    services: "Packing, unpacking",
    price: "20, 500",
    status: "completed",
    name: "uzair",
  },
  {
    id: 3,
    date: "24 march, 2023",
    company: "Shehroz & Co",
    services: "moving",
    price: "12, 500",
    status: "completed",
    name: "abdul",
  },
  {
    id: 1,
    date: "12 jan, 2023",
    company: "Shehroz & Co",
    services: "Packing",
    price: "12, 500",
    status: "completed",
    name: "haji",
  },
  {
    id: 3,
    date: "22 jul, 2023",
    company: "Anjum Movers",
    services: "Packing, unpacking",
    price: "5, 500",
    status: "completed",
    name: "janum",
  },
  {
    id: 4,
    date: "11 dec, 2022",
    company: "Shehroz & Co",
    services: "moving",
    price: "7, 200",
    status: "completed",
    name: "salman",
  },
];
